- name: datastore | Check volume group
  tags: &TAGS
    - docker.lvm
  command: "vgs {{ docker_lvm_vg }}"
  register: vg_status
  ignore_errors: yes

- name: datastore | Create | Physical Volume
  command: "pvcreate -f {{ docker_lvm_pv }}"
  when: vg_status is failed
  tags: *TAGS
- name: datastore | Create | Volume Group
  lvg:
    vg: "{{ docker_lvm_vg }}"
    pvs:
      - "{{ docker_lvm_pv }}"
    pesize: "4Mb"
  when: vg_status is failed
  tags: *TAGS
