- name: Setup datastore
  include_tasks: datastore.yml
  when: docker_lvm
  tags: &tags
    - docker.lvm
- name: Setup volumes
  include_tasks: volumes.yml
  when: docker_lvm and docker_lvm_volumes
  tags: *tags
